[project]
name = "mcp-upbank"
version = "0.1.0"
authors = [
  {name = "Navishkar Rao"},
]
description = "A MCP server for communicating with the Up Bank API"
readme = "README.md"
requires-python = ">=3.12.6"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
]
